name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: [3.8, 3.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@master

      - name: Setup python ${{ matrix.python_version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python_version }}

      - name: flake8
        run: |
          python -m pip install flake8
          flake8 -v --config=flake8rc .

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: [3.8, 3.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@master

      - name: Setup python ${{ matrix.python_version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python_version }}

      - name: Run tests
        run: |
          pip install pytest pytest-asyncio pytest-cov
          pytest -v --cov --cov-fail-under=100 --cov-report term-missing
